@CommunityToolkit.Aspire.Hosting.DurableTask.Scheduler.WebApi_HostAddress = http://localhost:5142

GET {{CommunityToolkit.Aspire.Hosting.DurableTask.Scheduler.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
